wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.10
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1646887350
    t:
      1:
      - 1
      - 2
      - 3
      3:
      - 16
      4: 3.8.10
      5: 0.12.10
      8:
      - 5
adam:
  desc: null
  value: false
artifact_alias:
  desc: null
  value: latest
batch_size:
  desc: null
  value: 2
bbox_interval:
  desc: null
  value: -1
bucket:
  desc: null
  value: ''
cache:
  desc: null
  value: null
cfg:
  desc: null
  value: models/yolov5l-LK-newBiFPN.yaml
data:
  desc: null
  value: ./data/VisDrone.yaml
data_dict:
  desc: null
  value:
    names:
    - pedestrian
    - people
    - bicycle
    - car
    - van
    - truck
    - tricycle
    - awning-tricycle
    - bus
    - motor
    nc: 10
    test: VisDrone/VisDrone2019-DET-test-dev/images
    train: VisDrone/VisDrone2019-DET-train/images
    val: VisDrone/VisDrone2019-DET-val/images
device:
  desc: null
  value: ''
entity:
  desc: null
  value: null
epochs:
  desc: null
  value: 200
evolve:
  desc: null
  value: null
exist_ok:
  desc: null
  value: false
freeze:
  desc: null
  value: 0
hyp:
  desc: null
  value:
    anchor_t: 3
    box: 0.07
    cls: 0.18
    cls_pw: 0.631
    copy_paste: 0.1
    degrees: 0.2
    fl_gamma: 0.0
    fliplr: 0.5
    flipud: 0.0
    hsv_h: 0.4
    hsv_s: 0.3
    hsv_v: 0.5
    iou_t: 0.2
    lr0: 0.0003
    lrf: 0.12
    mixup: 0.2
    momentum: 0.843
    mosaic: 1.0
    obj: 0.15
    obj_pw: 0.911
    perspective: 0.0
    scale: 0.4
    shear: 0.0
    translate: 0.0
    warmup_bias_lr: 0.05
    warmup_epochs: 2.0
    warmup_momentum: 0.5
    weight_decay: 0.00036
image_weights:
  desc: null
  value: false
imgsz:
  desc: null
  value: 1600
label_smoothing:
  desc: null
  value: 0.0
linear_lr:
  desc: null
  value: false
local_rank:
  desc: null
  value: -1
multi_scale:
  desc: null
  value: false
name:
  desc: null
  value: exp
noautoanchor:
  desc: null
  value: false
nosave:
  desc: null
  value: false
noval:
  desc: null
  value: false
patience:
  desc: null
  value: 100
project:
  desc: null
  value: runs/train
quad:
  desc: null
  value: false
rect:
  desc: null
  value: false
resume:
  desc: null
  value: false
save_dir:
  desc: null
  value: runs/train/exp
save_period:
  desc: null
  value: -1
single_cls:
  desc: null
  value: false
sync_bn:
  desc: null
  value: false
upload_dataset:
  desc: null
  value: false
weights:
  desc: null
  value: yolov5l.pt
workers:
  desc: null
  value: 8
